version: '3.8'
services:
  sapfimar-app:
    build: .
    container_name: sapfimar-v1
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 3000
    restart: always
    volumes:
      - ./dist:/app/dist